export enum MenuType {
  Help = "help",
  Settings = "settings",
  Community = "community",
  Leaderboard = "leader",
  Spectate = "spectate",
  RoomSettings = "roomSettings",
  CreateRoom = "createRoom",
  SearchRoom = "searchRoom",
  Shop = "shop",
  Dictionary = "dict",
  Invite = "invite",
  Practice = "practice",
  Ready = "ready",
  Start = "start",
  Exit = "exit",
  Replay = "replay",
}
